name: Symbonic
favicon: null
layout_spectrum: 0.50676
typography_spectrum: 0.23378
title: 'Digital Experience Agency for Film, Television, and Content Heroes'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aa2425'
    - '#cccccc'
    - '#ffffff'
    - '#000000'
    - '#808080'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: 8cba670c-f1cd-4843-8eed-c2342141cefd
    url: null
